Blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Posts.urls')),
]

Posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('blogs', views.blogs, name='blogs'),
    path('features', views.feature, name='feature'),
    path('post/<str:slug>', views.post, name='post'),
    path('search', views.search, name='search'),
    path('signup', views.signup, name='signup'),
    path('login', views.handlelogin, name='handlelogin'),
    path('logout', views.handlelogout, name='handlelogout'),
    path('addblog', views.add_blog, name='addblog'),
]

Posts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from .helpers import *
from froala_editor.fields import FroalaField

# Create your models here.
class Post(models.Model):
    author = models.ForeignKey(User,on_delete=models.CASCADE,blank=True, null=True)
    title = models.CharField(max_length=100)
    body = FroalaField()
    institute = models.CharField(max_length=100)
    slug = models.SlugField(max_length = 250, null = True, blank = True)
    created_at = models.DateTimeField(default=datetime.now, blank=True)
    
    def save(self , *args, **kwargs): 
        self.slug = generate_slug(self.title)
        super(Post, self).save(*args, **kwargs)

class Feature(models.Model):
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=100000)


class Comment(models.Model):
    post= models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name= models.CharField(max_length=200)
    body= models.TextField()
    date_added= models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return '%s - %s' % (self.post.title, self.name)

Posts/forms.py
from django import forms
from froala_editor.widgets import FroalaEditor

from .models import *


class BlogForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['body']


class commentForm(forms.ModelForm):
    class Meta:
        model= Comment
        fields=('name','body')
    

Posts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import redirect, render

from .forms import BlogForm, commentForm
from .models import Feature, Post

# Create your views here.

def index(request):
    post = Post.objects.last()
    context = {
        'post': post
    }
    return render(request, 'index.html', context)

def blogs(request):
    posts = Post.objects.all()
    context = {
        'posts': posts
    }
    return render(request, 'blogs.html', context)

def post(request, slug):
    post = Post.objects.get(slug=slug)
    model= commentForm
    
    if request.method=="POST":
        
        form= commentForm(request.POST)
        if form.is_valid() and request.user.is_authenticated:
            form = form.save(commit=False)
            form.post_id = post.id
            form.save()
            return redirect('/blogs')
        else:
            return redirect('/')
    context = {
        'post': post,
        'model': model
    }
    return render(request, 'post.html', context)

def feature(request):
    features = Feature.objects.all()
    context = {
        'features': features
    }
    return render(request, 'features.html', context)

def search(request):
    search = request.GET['search']
    if len(search) > 50 or len(search) == 0:
        posts = []
    else:
        posts = Post.objects.filter(title__icontains=search)
        institutePosts = Post.objects.filter(institute__icontains=search)
        posts = posts.union(institutePosts)
    context = {
        'posts': posts,
        'search': search
    }
    return render(request, 'search.html', context)

def signup(request):
    if request.method == 'POST':
        email = request.POST['email']
        username = request.POST['username']
        password = request.POST['password']
        password1 = request.POST['password1']
        if len(username) > 15:
            messages.error(request, 'Your username must be under 15 characters')
            return redirect('/')
        if password != password1:
            messages.error(request, 'passwords donot match')
            return redirect('/')            
        myUser = User.objects.create_user(username, email, password)
        myUser.save()
        login(request, myUser)
        return redirect('/')
    else:
        return HttpResponse('404 - Not Found')

def handlelogin(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Invalid credentials. Please try again')
            return redirect('/')
    else:
        return HttpResponse('404 - Not Found')

def handlelogout(request):
    logout(request)
    return redirect('/')

def add_blog(request):
    # context = {}
    
    context = {'form' : BlogForm}
    try:
        if request.method == 'POST':
            form = BlogForm(request.POST)
            # print(request.FILES)
            title = request.POST.get('title')
            institute = request.POST.get('institute')

            if form.is_valid():
                body = form.cleaned_data['body']

            blog_obj = Post.objects.create(
                title = title, 
                body = body,
                institute = institute,
            )
            return redirect('/blogs')
            
            
    
    except Exception as e :
        print(e)
    
    return render(request , 'addblog.html' , context)

templates/addblog.html
{% extends 'base.html' %}

{% block title %}Posts{% endblock title %}
{% block body %}
<div class="container mt-5">
    <form method="post" class="mt-5 pt-5 mb-5 pb-5" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <label>Enter blog title</label>
                <input type="text" class="form-control" placeholder="Enter title" name="title">
            </div>
            <div class="col-md-12">
                <label>Enter institute</label>
                <input type="text" class="form-control" placeholder="Enter institute" name="institute">
            </div>

            <div class="col-md-12">
                {{form.media}}
                {{form.as_p}}
            </div>
        </div>

        <button type="submit" class="btn btn-primary mt-4">Create Blog</button>

    </form>

</div>

{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" href="{% static 'styles.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
		integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
		crossorigin="anonymous"></script>

</head>

<body>

	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container-fluid">
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
				aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<a class="navbar-brand ls" href="/">BlogBook</a>
			<div class="collapse navbar-collapse" id="navbarTogglerDemo03">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="/">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="/blogs">Blogs</a>
					</li>
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="/features">Features</a>
					</li>
					{% if user.is_authenticated %}
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="/addblog">Create Blog</a>
					</li>
					{% endif %}
				</ul>
				<form method="get" action='/search' class="d-flex">
					<input class="form-control mx-2" type="search" placeholder="Search" aria-label="Search"
						name="search" id="search">
					<button class="btn btn-outline-success mx-3" type="submit">Search</button>
				</form>
			</div>
		</div>

		{% if user.is_authenticated %}
		<button type="button" class="btn btn-primary mx-1">{{request.user}}</button>
		<a href="/logout" method="POST"><button type="button" class="btn btn-primary mx-1">Logout</button></a>
		{% else %}
		<button type="button" class="btn btn-primary mx-1" data-bs-toggle="modal"
			data-bs-target="#loginmodal">Login</button>

		<div class="modal fade" id="loginmodal" tabindex="-1" aria-labelledby="loginmodalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="loginmodalLabel">LOGIN</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						<form action="/login" method="POST">
							<div class="mb-3">
								<label for="username" class="form-label">Username</label>
								<input type="text" class="form-control" id="username" name="username"
									aria-describedby="emailHelp" required>
							</div>
							<div class="mb-3">
								<label for="password" class="form-label">Password</label>
								<input type="password" class="form-control" id="password" name="password" required>
							</div>
							{% csrf_token %}
							<button type="submit" class="btn btn-primary">Login</button>
						</form>
					</div>
				</div>
			</div>
		</div>

		<button type="button" class="btn btn-secondary mx-2" data-bs-toggle="modal"
			data-bs-target="#signupModal">Signup</button>

		<div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<h5 class="modal-title" id="exampleModalLabel">Signup</h5>
						<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
					</div>
					<div class="modal-body">
						<form action="/signup" method="POST">
							<div class="mb-3">
								<label for="email" class="form-label">Email address</label>
								<input type="email" class="form-control" id="signupemail" name="email"
									aria-describedby="emailHelp" required>
								<div id="emailHelp" class="form-text">We'll never share your email with anyone else.
								</div>
							</div>
							<div class="mb-3">
								<label for="user" class="form-label">Username</label>
								<input type="text" class="form-control" id="signupusername" name="username"
									aria-describedby="emailHelp" required>
							</div>
							<div class="mb-3">
								<label for="password" class="form-label">Password</label>
								<input type="password" class="form-control" id="signup-password" name="password"
									required>
							</div>
							<div class="mb-3">
								<label for="password" class="form-label">Re enter Password</label>
								<input type="password" class="form-control" id="signup-password1" name="password1"
									required>
							</div>
							{% csrf_token %}
							<button type="submit" class="btn btn-primary">Signup</button>
						</form>
					</div>
				</div>
			</div>
		</div>
		{% endif %}
	</nav>

	{% for message in messages %}
	<h5>{{message}}</h5>
	{% endfor %}
	</div>
	<div class="container-fluid">
		{% block body %}{% endblock body %}
	</div>


</body>

</html>

templates/blogs.html
{% extends 'base.html' %}

{% block title %}Blogs{% endblock title %}

{% block body %}
<div class="row">
	{% for post in posts reversed %}
	<div class="col-sm-4">
		<div class="card text-dark bg-light mb-3 shadow p-3 mb-5 bg-body rounded">
			<div class="card-body">
				<h5 class="card-title">{{post.title}}</h5>
				<h6 class="card-subtitle mb-2 text-muted">{{post.created_at}}</h6>
				<p class="card-text">{{post.body|striptags|truncatewords:20}}</p>
				<a href="/post/{{post.slug}}" class="card-link">Read More</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock body %}

templates/features.html
{% extends 'base.html' %}

{% block title %}BlogBook{% endblock title %}



{% block body %}
<div class="container-fluid bg-dark text-light p-5">
    <div class="container bg-dark p-5">
        <h1 class="display-4 text-center">Welcome to BlogBook</h1>
        <hr>
		<h6 class="text-xxl-end"> Tired of so much data available on the Internet? </h6> 
		<h6 class="text-xxl-end"> Worry not, here you will find only curated content </h6>
    </div>
</div>
<div class="row">
	{% for feature in features %}
	<div class="col-sm-4">
		<div class="card border-dark mb-3 shadow p-3 mb-5 bg-body rounded">
			<div class="card-header">{{feature.title}}</div>
			<div class="card-body">
				<p class="card-text">{{feature.body}}</p>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock body %}

templates/index.html
{% extends 'base.html' %}

{% block title %}BlogBook{% endblock title %}

{% block body %}

<div class="container-fluid bg-dark text-light p-5">
    <div class="container bg-dark p-5">
        <h1 class="display-4 text-center">Welcome to BlogBook</h1>
        <hr>
		<h5 class="text-xxl-end"> Are you ready to take your career to a new level? </h5>
    </div>
</div>


<div class="row">
	<div class="col-sm-4">
		<div class="card text-dark bg-light mb-3 shadow p-3 mb-5 bg-body rounded">
			<div class="card-body">
				<h5 class="card-title">{{post.title}}</h5>
				<h6 class="card-subtitle mb-2 text-muted">{{post.created_at}}</h6>
				<p class="card-text">{{post.body|striptags|truncatewords:20}}</p>
				<a href="/post/{{post.slug}}" class="card-link">Read More</a>
			</div>
		</div>
	</div>
</div>
{% endblock body %}

templates/instituteList.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>BlogBook</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
                aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="/">BlogBook</a>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/features">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/instituteList">Institutes</a>
                    </li>
                </ul>
                <form method="get" action="/searchByInstitute" class="d-flex">
                    <input class="form-control mx-2" type="search" placeholder="Search" aria-label="Search"
                        name="search" id="search" />
                    <button class="btn btn-outline-success mx-3" type="submit">
                        Search
                    </button>
                </form>
            </div>
        </div>

        {% if user.is_authenticated %}
        <button type="button" class="btn btn-primary mx-1">
            {{request.user}}
        </button>
        <a href="/logout" method="POST"><button type="button" class="btn btn-primary mx-1">Logout</button></a>
        {% else %}
        <button type="button" class="btn btn-primary mx-1" data-bs-toggle="modal" data-bs-target="#loginmodal">
            Login
        </button>

        <div class="modal fade" id="loginmodal" tabindex="-1" aria-labelledby="loginmodalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="loginmodalLabel">LOGIN</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="/login" method="POST">
                            <div class="mb-3">
                                <label for="username" class="form-label">Username</label>
                                <input type="text" class="form-control" id="username" name="username"
                                    aria-describedby="emailHelp" required />
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="password" name="password" required />
                            </div>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

        <button type="button" class="btn btn-secondary mx-2" data-bs-toggle="modal" data-bs-target="#signupModal">
            Signup
        </button>

        <div class="modal fade" id="signupModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Signup</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form action="/signup" method="POST">
                            <div class="mb-3">
                                <label for="email" class="form-label">Email address</label>
                                <input type="email" class="form-control" id="signupemail" name="email"
                                    aria-describedby="emailHelp" required />
                                <div id="emailHelp" class="form-text">
                                    We'll never share your email with anyone else.
                                </div>
                            </div>
                            <div class="mb-3">
                                <label for="user" class="form-label">Username</label>
                                <input type="text" class="form-control" id="signupusername" name="username"
                                    aria-describedby="emailHelp" required />
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Password</label>
                                <input type="password" class="form-control" id="signup-password" name="password"
                                    required />
                            </div>
                            <div class="mb-3">
                                <label for="password" class="form-label">Re enter Password</label>
                                <input type="password" class="form-control" id="signup-password1" name="password1"
                                    required />
                            </div>
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Signup</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </nav>

    <div class="row">
		<div class="col-sm-6">
			<div class="card text-dark bg-light mb-3 shadow p-3 mb-5 bg-body rounded">
				<div class="card-body">
					<h5 class="card-title">If you donot see you institute then please contact me on my email: tanmayraj292000@gmail.com</h5>
				</div>
			</div>
		</div>
	</div>

    <div class="row">
        {% for institute in institutes %}
        <div class="col-sm-2">
            <div class="card text-dark bg-light mb-3 shadow p-3 mb-5 bg-body rounded">
                <div class="card-body">
                    <form method="get" action="/searchByInstitute" class="d-flex">
                        <div class=" text-center"> 
                        <button class="btn btn-outline-success" type="submit" name="search">
                            {{institute.name}}
                        </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</body>

</html>

templates/post.html
{% extends 'base.html' %}

{% block title %}BlogBook{% endblock title %}
{% block body %}
<div class="shadow p-3 mb-5 bg-body rounded">
	<h1>{{post.title}}</h1>
	<h5>{{post.institute}}</h5>
	<h5>{{post.created_at}}</h5>
	<p>{{post.body|safe}}</p>
</div>
</body>

<div class="social-share mb-3">
	<a><span class="d-none d-sm-inline font-weight-bold">Share: </span></a>
	<!-- share facebook -->
	<a class="btn btn-light btn-sm blank-windows"
		href="https://www.facebook.com/sharer.php?u=http://localhost:8000{% url 'post' slug=post.title %}"
		title="Share to facebook"><i class="fa fa-facebook"></i> <span class="d-none d-sm-inline">Facebook</span></a>
	<!-- share twitter -->
	<a class="btn btn-light btn-sm blank-windows"
		href="https://www.twitter.com/share?url=http://localhost:8000{% url 'post' slug=post.title %}"
		title="Share to twitter"><i class="fa fa-twitter"></i> <span class="d-none d-sm-inline">Twitter</span></a>
	<!-- share linkedin -->
	<a class="btn btn-light btn-sm blank-windows"
		href="https://www.linkedin.com/shareArticle?mini=true&amp;url=http://localhost:8000{% url 'post' slug=post.title %}"
		title="Share to Linkedin"><i class="fa fa-linkedin"></i> <span class="d-none d-sm-inline">Linkedin</span></a>
	<!-- share to whatsapp -->
	<a class="btn btn-light btn-sm  blank-windows"
		href="whatsapp://send?text=Read&nbsp;the&nbsp;article-{{ post.title }}&nbsp;on&nbsp;http://localhost:8000{% url 'post' slug=post.title %}"
		data-action="share/whatsapp/share" title="Share to whatsapp"><i class="fa fa-whatsapp"></i> <span
			class="d-none d-sm-inline">Whatsapp</span></a>
	<!-- share via email -->
	<a class="btn btn-light btn-sm"
		href="mailto:?subject=Your&nbsp;post&nbsp;title&amp;body=Read&nbsp;complete&nbsp;article&nbsp;in&nbsp;here&nbsp;http://localhost:8000/{% url 'post' slug=post.title %}"
		title="Share by Email"><i class="fa fa-envelope"></i> <span class="d-none d-sm-inline">Email</span></a>
</div>
<!-- social share -->

<div>
	<div class="block-title-6">
		<h4 class="h5 border-primary border-2">
			<!-- <span class="bg-primary text-white"> -->
			Comments
		</h4>
	</div>
	<div class="container">
		{% if not post.comments.all %}
		<strong> No comments Yet... </strong><br>
		{% else %}
		<ol class="comment-list">
			{% for comment in post.comments.all %}
			<li class="comment even thread-even depth-1" id="comment-2">
				<div id="div-comment-2" class="user-comment u-hover">
					<footer class="comment-author vcard">
						<img alt=""
							src="https://secure.gravatar.com/avatar/738b90e0b42b283d92dfe2e92456327a?s=75&amp;d=mm&amp;r=g"
							srcset="https://secure.gravatar.com/avatar/738b90e0b42b283d92dfe2e92456327a?s=150&amp;d=mm&amp;r=g 2x"
							class="avatar avatar-75 photo" height="75" width="75" loading="lazy">
						<div class="title-comments">
							<div class="authors">
								<a target="_blank" href="#" rel="external nofollow ugc" class="url">{{comment.name}}</a>
							</div> <span class="text-muted dates small">
								{{comment.date_added}} </span>
						</div>
					</footer>
					<em class="comment">{{comment.body}}</em><br>
					<div class="comment-content">
					</div>
				</div>
			</li><!-- #comment-## -->
			{% endfor %}

		</ol>
		{% endif %}
	</div>


</div>

<div id="comments" class="mb-5">



	<div id="respond" class="comment-respond mt-5">

		<h3 id="reply-title" class="comment-reply-title">Liked the post? Write something good about it!<small><a
					rel="nofollow" id="cancel-comment-reply-link" href="index.html#respond" style="display:none;">Cancel
					reply</a></small></h3>
		<form action="" method="POST" id="commentform" class="comment-form" novalidate="">
			{% csrf_token %}
			<p class="comment-notes"> Required fields are marked <span class="required">*</span></p>
			<div class="form-group comment-form-comment">

				<textarea class="form-control" id="id_body" placeholder="Comment *" cols="45" rows="8" required=""
					name="body" required id="id_body"></textarea>

			</div>
			<br>
			<div class="form-group comment-form-author">

				<input type="text" name="name" required="" id="id_name" class="form-control" placeholder="Name *"
					value="" size="30" aria-required="true">
			</div>
			{% comment %} <div class="form-group comment-form-email">
				<input class="form-control" id="email" placeholder="Email *" name="email" type="email" value=""
					size="30" aria-required="true" required="">
			</div> {% endcomment %}
			<!-- <div class="form-group form-check comment-form-cookies-consent"><input class="form-check-input"
					id="wp-comment-cookies-consent" name="wp-comment-cookies-consent" type="checkbox" value="yes">
				<label class="form-check-label" for="wp-comment-cookies-consent">Save my name, email in this browser
					for the next time I comment</label>
			</div> -->
			<br>
			<p class="form-submit">
				<input name="submit" type="submit" id="submit" class="btn btn-primary" value="Post Comment">
				<input type="hidden" name="comment_post_ID" value="66" id="comment_post_ID">
				<input type="hidden" name="comment_parent" id="comment_parent" value="0">
			</p>
		</form>
	</div>

	<!-- #respond -->
</div>

{% endblock body %}

templates/search.html
{% extends 'base.html' %}

{% block title %}Search Results{% endblock title %}

{% block body %}
	<div class="row">
		<div class="col-sm-3">
			<div class="card text-dark bg-light mb-3 shadow p-3 mb-5 bg-body rounded">
				<div class="card-body">
					<h5 class="card-title">Search Results:</h5>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		{% if posts|length == 0 %}
		<p>Your search - <b>{{search|truncatewords:10}} </b> - did not match any documents.</p>
		<h5>Suggestions:</h5>
		<ul class="list-group list-group-flush">
			<li class="list-group-item">Make sure that all words are spelled correctly.</li>
			<li class="list-group-item">Try different keywords.</li>
			<li class="list-group-item">Try more general keywords.</li>
			<li class="list-group-item">Try fewer keywords.</li>
			<l1>
				</li>
		</ul>
		{% else %}
		<h5>{{search}}</h5>
		{% endif %}
		{% for post in posts reversed %}
		<div class="col-sm-4">
			<div class="card text-dark bg-light mb-3 shadow p-3 mb-5 bg-body rounded">
				<div class="card-body">
					<h5 class="card-title">{{post.title}}</h5>
					<h6 class="card-subtitle mb-2 text-muted">{{post.created_at}}</h6>
					<p class="card-text">{{post.body|striptags|truncatewords:20}}</p>
					<a href="/post/{{post.slug}}" class="card-link">Read More</a>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
{% endblock body %}